#!/bin/busybox sh
#
# Example command line args:
#
#   root_lv=vgsys/lvroot usr_lv=vgsys/lvusr mount_usr=1 real_root=LABEL=/ usr=LABEL=/usr

cmdline() {
    local value
    value=" $(cat /proc/cmdline) "
    value="${value##* $1=}"
    value="${value%% *}"
    [ "$value" != "" ] && echo "$value"
}

rescue_shell() {
    echo "Something went wrong. Dropping you to a shell."
    busybox --install -s
    exec /bin/sh
}

echo "Mounting dev proc sys"
mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys

echo "Parsing args"
root_lv=$(cmdline "root_lv")
: ${root_lv:="vgsys/lvroot"}
usr_lv=$(cmdline "usr_lv")
: ${usr_lv:="vgsys/lvusr"}
mount_usr=$(cmdline "mount_usr")
: ${mount_usr:=1}
root_fs=$(cmdline "real_root")
: ${root_fs:="LABEL=/"}
usr_fs=$(cmdline "usr")
: ${usr_fs:="LABEL=/usr"}

lvm vgscan --mknodes
echo "Enabling root lvm $root_lv"
lvm lvchange -aly $root_lv
if [ $mount_usr -eq 1 ]; then
    echo "Enabling usr lvm $usr_lv"
    lvm lvchange -aly $usr_lv
fi

echo "Mounting root $root_fs"
mount -o ro $(findfs $root_fs) /mnt/root || rescue_shell

if [ $mount_usr -eq 1 ]; then
    echo "Mounting usr $usr_fs for udev"
    mount -o rw $(findfs $usr_fs) /mnt/root/usr || rescue_shell
fi

echo "Cleaning up"
umount /proc
umount /sys
umount /dev

echo "Switching root"
exec switch_root /mnt/root /sbin/init
