#!/bin/busybox sh


rescue_shell() {
    echo "Something went wrong. Dropping you to a shell."
    busybox --install -s
    exec /bin/sh
}

echo "Mounting dev proc sys"
mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys

echo "Enabling lvm"
lvm vgscan --mknodes
lvm lvchange -a ly vgsys/lvroot
lvm lvchange -a ly vgsys/lvusr

echo "Mounting root"
mount -o ro /dev/mapper/vgsys-lvroot /mnt/root || rescue_shell

echo "Mounting usr for udev"
mount -o rw /dev/mapper/vgsys-lvusr /mnt/root/usr || rescue_shell

echo "Cleaning up"
umount /proc
umount /sys
umount /dev

echo "Switching root"
exec switch_root /mnt/root /sbin/init
